# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-03 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('external_user_ids', '0003_auto_20200224_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateExternalIdsConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_list', models.TextField(blank=True, default='', help_text='List of user IDs separated by a comma to generate ExternalIds for.')),
                ('external_id_type', models.ForeignKey(help_text='The type of external ID to generate for the listed users', on_delete=django.db.models.deletion.CASCADE, to='external_user_ids.ExternalIdType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
